#include <gtest/gtest.h>

#include <triqs_xca/atom_diag_utils.hpp>
#include <triqs_xca/block_sparse/atom_diag_utils.hpp>

using nda::range;

using cppdlr::_;
using cppdlr::build_dlr_rf;
using cppdlr::imtime_ops;
using cppdlr::k_it;

using triqs::operators::c;
using triqs::operators::c_dag;
using triqs::operators::n;

using triqs_xca::atom_diag::get_full_h_atomic;
using triqs_xca::atom_diag::get_full_operator_matrix;
using triqs_xca::atom_diag::get_hamiltonian_blocks;
using triqs_xca::atom_diag::get_operators;

/**
 * @brief Creates a two-orbital Hamiltonian with spin and constructs the atom_diag object.
 *
 * @details Builds H = sum_i [ U n_up,i n_do,i + mu (n_up,i + n_do,i) + V (c†_up,i c_do,i + h.c.) ]
 * with norb=2, mu=0.25, U=1.0, V=0.1 by default. Orbital ordering: do 0, do 1, up 0, up 1.
 *
 * @param[in] norb Number of orbitals (default 2)
 * @param[in] mu Chemical potential (default 0.25)
 * @param[in] U On-site interaction strength (default 1.0)
 * @param[in] V Inter-orbital coupling strength (default 0.1)
 * @return triqs::atom_diag::atom_diag<true> object representing the Hamiltonian
 */
triqs::atom_diag::atom_diag<true> make_two_orbital_ad(int norb = 2, double mu = 0.25, double U = 1.0, double V = 0.1) {

  triqs::operators::many_body_operator_complex H;
  triqs::atom_diag::fundamental_operator_set fop_set;

  // Build Hamiltonian and fundamental operator set
  for (int i = 0; i < norb; ++i) {
    H += U * n("up", i) * n("do", i) + mu * (n("up", i) + n("do", i)) + V * (c_dag("up", i) * c("do", i) + c_dag("do", i) * c("up", i));
    fop_set.insert("do", i);
  }
  for (int i = 0; i < norb; ++i) { fop_set.insert("up", i); }

  return {H, fop_set}; // triqs::atom_diag::atom_diag<true>(H, fop_set);
}

/**
 * @brief Builds DLR hybridization coefficients for the two-orbital model.
 *
 * Constructs a 4x4 hybridization function Delta(tau) on the DLR grid from two bath levels
 * e = {-3.3, 2.3} with hopping t=1.0 and spin-flip coupling s=0.5, at beta=2.0
 * and DLR cutoff Lambda=20. Returns the DLR coefficients of Delta(tau).
 *
 * The two orbitals of make_two_orbital_ad() are decoupled, so the field operators fall into the two symmetry sets {do 0, up 0} and
 * {do 1, up 1}, and the off-diagonal entries are restricted to the same-orbital, opposite-spin pairs (0, 2) and (1, 3). Only the upper
 * triangle is filled, which makes the bar expectations sensitive to the hyb_coeffs(l, k, m) index order.
 */
nda::array<dcomplex, 3> make_hyb_coeffs() {
  double s      = 0.5;
  double t      = 1.0;
  double beta   = 2.0;
  double Lambda = 10 * beta;
  double eps    = 1.0e-6;
  int norb      = 2;
  nda::array<double, 1> e{-3.3 * t, 2.3 * t};

  auto dlr_rf        = build_dlr_rf(Lambda, eps);
  auto itops         = imtime_ops(Lambda, dlr_rf);
  auto const &dlr_it = itops.get_itnodes();
  auto dlr_it_abs    = cppdlr::rel2abs(dlr_it);
  int r              = itops.rank();

  auto Jt = nda::array<dcomplex, 3>(r, 1, 1);
  for (int i = 0; i <= 1; i++) {
    for (int u = 0; u < r; u++) { Jt(u, 0, 0) += k_it(dlr_it_abs(u), e(i), beta); }
  }

  // orbital index order: do 0, do 1, up 0, up 1. same level <-> same parity index
  auto Deltat = nda::array<dcomplex, 3>(r, 2 * norb, 2 * norb);
  for (int i = 0; i < Deltat.extent(1); i++) {
    for (int j = i; j < Deltat.extent(2); j++) {
      if (i == j) {
        Deltat(_, i, j) = Jt(_, 0, 0);
      } else if ((i == 0 && j == 2) || (i == 1 && j == 3)) { // same orbital, opposite spin: within one symmetry set
        Deltat(_, i, j) = s * Jt(_, 0, 0);
      }
    }
  }
  Deltat = t * t * Deltat;

  return itops.vals2coefs(Deltat);
}

/**
 * @brief Builds expected annihilation and creation operator matrices in the Fock basis.
 *
 * For 2*norb fermionic modes, constructs the N x N matrix representation of c_oidx and c†_oidx
 * (where N = 2^(2*norb)) using the standard fermionic anticommutation sign convention.
 *
 * @param[in] norb Number of orbitals (total flavors = 2*norb for spin-1/2)
 * @return Pair of (c_mats, cdag_mats), each of shape (2*norb, N, N)
 */
std::pair<nda::array<dcomplex, 3>, nda::array<dcomplex, 3>> make_expected_fock_operators(int norb) {
  int nflav      = 2 * norb;    // number of particle flavors (spin up and down for each orbital)
  long N         = 1L << nflav; // 2^(2*norb) total Fock states
  auto c_mats    = nda::zeros<dcomplex>(nflav, N, N);
  auto cdag_mats = nda::zeros<dcomplex>(nflav, N, N);

  // Slick way of filling in the c and c† matrices using bit manipulation to determine signs and state transitions generated by Claude
  // This has been verified to produce the same matrices as from a previous atom_diag python run.
  for (int oidx = 0; oidx < nflav; ++oidx) {
    for (long n = 0; n < N; ++n) {
      if (n & (1L << oidx)) {
        long m                = n ^ (1L << oidx);
        int sign              = (__builtin_popcountl(n & ((1L << oidx) - 1)) % 2 == 0) ? 1 : -1;
        c_mats(oidx, m, n)    = sign;
        cdag_mats(oidx, n, m) = sign;
      }
    }
  }
  return {std::move(c_mats), std::move(cdag_mats)};
}

/**
 * @brief Tests the computation of the full Hamiltonian and operator matrices from the atom_diag object.
 * 
 * This test creates a simple two-orbital Hamiltonian with known parameters, constructs the corresponding atom_diag object, and then uses the 
 * get_full_h_atomic and get_full_operator_matrix functions to compute the full Hamiltonian and operator matrices. The results are compared against 
 * expected matrices that were generated from a reference atom_diag python run. The test checks that the computed matrices match the expected ones 
 * within numerical precision limits.
 */
TEST(AtomDiagUtils, get_matrices) {
  // --- atom_diag setup ---
  int norb = 2;
  auto ad  = make_two_orbital_ad();

  // --- Get full Hamiltonian and operator matrices ---
  // Get full Hamiltonian matrix
  auto H_mat    = get_full_h_atomic(ad);
  std::size_t N = H_mat.extent(0);
  // The Hamiltonian has spin, so there are 2 * norb particle flavors
  nda::array<dcomplex, 3> c_mats(2 * norb, N, N), cdag_mats(2 * norb, N, N);
  for (int oidx = 0; oidx < 2 * norb; ++oidx) {
    auto c_mat            = get_full_operator_matrix(ad, oidx, false);
    auto cdag_mat         = get_full_operator_matrix(ad, oidx, true);
    c_mats(oidx, _, _)    = c_mat;
    cdag_mats(oidx, _, _) = cdag_mat;
  }

  // --- Expected matrices ---
  // Expected Hamiltonian matrix generated from atom_diag python run
  auto expected_H_mat    = nda::zeros<dcomplex>((long)N, (long)N);
  expected_H_mat(1, 1)   = 0.25;
  expected_H_mat(1, 4)   = 0.1;
  expected_H_mat(2, 2)   = 0.25;
  expected_H_mat(2, 8)   = 0.1;
  expected_H_mat(3, 3)   = 0.5;
  expected_H_mat(3, 6)   = -0.1;
  expected_H_mat(3, 9)   = 0.1;
  expected_H_mat(4, 1)   = 0.1;
  expected_H_mat(4, 4)   = 0.25;
  expected_H_mat(5, 5)   = 1.5;
  expected_H_mat(6, 3)   = -0.1;
  expected_H_mat(6, 6)   = 0.5;
  expected_H_mat(6, 12)  = -0.1;
  expected_H_mat(7, 7)   = 1.75;
  expected_H_mat(7, 13)  = -0.1;
  expected_H_mat(8, 2)   = 0.1;
  expected_H_mat(8, 8)   = 0.25;
  expected_H_mat(9, 3)   = 0.1;
  expected_H_mat(9, 9)   = 0.5;
  expected_H_mat(9, 12)  = 0.1;
  expected_H_mat(10, 10) = 1.5;
  expected_H_mat(11, 11) = 1.75;
  expected_H_mat(11, 14) = -0.1;
  expected_H_mat(12, 6)  = -0.1;
  expected_H_mat(12, 9)  = 0.1;
  expected_H_mat(12, 12) = 0.5;
  expected_H_mat(13, 7)  = -0.1;
  expected_H_mat(13, 13) = 1.75;
  expected_H_mat(14, 11) = -0.1;
  expected_H_mat(14, 14) = 1.75;
  expected_H_mat(15, 15) = 3.0;

  // Expected creation and annihilation operator matrices from standard Fock-space representation
  auto [expected_c_mats, expected_cdag_mats] = make_expected_fock_operators(norb);

  ASSERT_LE(nda::max_element(nda::abs(H_mat - expected_H_mat)), 1e-13);
  ASSERT_LE(nda::max_element(nda::abs(c_mats - expected_c_mats)), 1e-13);
  ASSERT_LE(nda::max_element(nda::abs(cdag_mats - expected_cdag_mats)), 1e-13);
}

/**
 * @brief Tests the extraction of Hamiltonian blocks from the atom_diag object.
 * 
 * This test creates a simple two-orbital Hamiltonian with known parameters, constructs the corresponding atom_diag object, and then uses the 
 * get_hamiltonian_blocks function to extract the Hamiltonian blocks and their corresponding block indices. A block index of 0 at index i indicates 
 * that there is a nonzero block in block column i (which is also block row i, since H is block-diagonal). The results are compared against expected 
 * blocks and indices that were generated from a reference atom_diag python run. The test checks that the computed blocks and indices match the 
 * expected ones within numerical precision limits.
 */
TEST(AtomDiagUtils, hamiltonian_blocks) {
  // --- atom_diag setup ---
  auto ad = make_two_orbital_ad();

  auto h_tuple    = get_hamiltonian_blocks(ad);
  auto blocks     = std::get<0>(h_tuple);
  auto block_inds = std::get<1>(h_tuple);

  // --- Expected blocks and indices ---
  std::vector<nda::matrix<dcomplex>> expected_blocks = {
     nda::matrix<dcomplex>{{
        0.0,
     }},
     nda::matrix<dcomplex>{{0.25, 0.1}, {0.1, 0.25}},
     nda::matrix<dcomplex>{{0.25, 0.1}, {0.1, 0.25}},
     nda::matrix<dcomplex>{{0.5, -0.1, 0.1, 0}, {-0.1, 0.5, 0, -0.1}, {0.1, 0, 0.5, 0.1}, {0, -0.1, 0.1, 0.5}},
     nda::matrix<dcomplex>{{1.5}},
     nda::matrix<dcomplex>{{1.5}},
     nda::matrix<dcomplex>{{1.75, -0.1}, {-0.1, 1.75}},
     nda::matrix<dcomplex>{{1.75, -0.1}, {-0.1, 1.75}},
     nda::matrix<dcomplex>{{3.0}}};

  nda::vector<int> expected_block_inds = {-1, 0, 0, 0, 0, 0, 0, 0, 0};

  for (size_t i = 0; i < blocks.size(); ++i) { ASSERT_LE(nda::max_element(nda::abs(blocks[i] - expected_blocks[i])), 1e-13); }
  ASSERT_EQ(block_inds, expected_block_inds);
}

/**
 * @brief Tests the construction of the BlockOpSymQuartet object containing the creation and annihilation operators.
 * 
 * This test creates a simple two-orbital Hamiltonian with known parameters, constructs the corresponding atom_diag object, constructs a 
 * set of hybridization coefficients, and then uses the get_operators function to construct the BlockOpSymQuartet object containing the creation and 
 * annihilation operators. The test checks that the resulting BlockOpSymQuartet has the expected symmetry set labels and that the operator blocks 
 * match expected blocks that were generated from a reference atom_diag python run, within numerical precision limits.
 */
TEST(AtomDiagUtils, operators) {
  // --- atom_diag setup ---
  auto ad = make_two_orbital_ad();

  // --- Hybridization setup ---
  auto hyb_coeffs = make_hyb_coeffs();

  // --- Get creation and annihilation operators ---
  auto [Fq, sym_set_labels] = get_operators(ad, hyb_coeffs);

  // --- Expected symmetry set labels ---
  nda::vector<int> expected_sym_set_labels{0, 1, 0, 1}; // do 0 and up 0 have the same sparsity pattern, as do do 1 and up 1
  ASSERT_EQ(sym_set_labels, expected_sym_set_labels);

  // check that hyb_coeffs has off-diagonal entries within a symmetry set
  ASSERT_GT(nda::max_element(nda::abs(hyb_coeffs(_, 0, 2))), 1.0e-6);
  ASSERT_GT(nda::max_element(nda::abs(hyb_coeffs(_, 1, 3))), 1.0e-6);
  ASSERT_EQ(sym_set_labels(0), sym_set_labels(2));
  ASSERT_EQ(sym_set_labels(1), sym_set_labels(3));

  // --- Expected Fs and F_dags blocks ---
  auto [expected_c_mats_fock, expected_cdag_mats_fock] = make_expected_fock_operators(2);
  // Get Fock space sizes and build permutation from ad subspace ordering to original Fock basis
  std::vector<size_t> fock_sizes;
  std::vector<long> perm; // perm[i] = original Fock state index at position i in subspace-ordered basis
  for (int s = 0; s < ad.n_subspaces(); ++s) {
    auto fock_states = ad.get_fock_states(s);
    fock_sizes.push_back(fock_states.size());
    for (auto state : fock_states) { perm.push_back(static_cast<long>(state)); }
  }
  // Build block_starts from fock_sizes
  std::vector<size_t> block_starts;
  for (int s = 0; s < ad.n_subspaces(); ++s) { block_starts.push_back(block_starts.empty() ? 0 : block_starts.back() + fock_sizes[s - 1]); }
  size_t N = block_starts.back() + fock_sizes.back();
  block_starts.push_back(N); // add end index for easy slicing

  // Permute expected matrices into ad subspace ordering
  long nflav              = expected_c_mats_fock.extent(0);
  auto expected_c_mats    = nda::zeros<dcomplex>(nflav, (long)N, (long)N);
  auto expected_cdag_mats = nda::zeros<dcomplex>(nflav, (long)N, (long)N);
  for (int oidx = 0; oidx < nflav; ++oidx) {
    for (size_t i = 0; i < N; ++i) {
      for (size_t j = 0; j < N; ++j) {
        expected_c_mats(oidx, i, j)    = expected_c_mats_fock(oidx, perm[i], perm[j]);
        expected_cdag_mats(oidx, i, j) = expected_cdag_mats_fock(oidx, perm[i], perm[j]);
      }
    }
  }

  // Build mapping from symmetry set index to orbital indices
  std::vector<std::vector<int>> sym_set_orbitals(Fq.Fs.size());
  for (int i = 0; i < sym_set_labels.size(); ++i) { sym_set_orbitals[sym_set_labels[i]].push_back(i); }

  // Helper: compare BlockOpSymSet (3D blocks) against dense expected matrix (nflav x N x N)
  auto check_sym_sets = [&](const auto &sets, const auto &expected_mats) {
    for (size_t f = 0; f < sets.size(); ++f) {
      auto &Fset        = sets[f];
      auto &orb_indices = sym_set_orbitals[f];
      for (int i = 0; i < Fset.get_num_block_cols(); ++i) {
        int b_ix = Fset.get_block_index(i);
        if (b_ix != -1) {
          auto block = Fset.get_block(i);
          for (size_t k = 0; k < orb_indices.size(); ++k) {
            auto expected_block =
               expected_mats(orb_indices[k], range(block_starts[b_ix], block_starts[b_ix + 1]), range(block_starts[i], block_starts[i + 1]));
            ASSERT_LE(nda::max_element(nda::abs(block(k, _, _) - expected_block)), 1e-13);
          }
        } else {
          for (int orb_index : orb_indices) {
            auto expected_block = expected_mats(orb_index, _, range(block_starts[i], block_starts[i + 1]));
            ASSERT_LE(nda::max_element(nda::abs(expected_block)), 1e-13);
          }
        }
      }
    }
  };

  // Helper: compare BlockOpSymSetBar (4D blocks) against dense expected matrix (nflav x p x N x N)
  auto check_sym_set_bars = [&](const auto &sets, const auto &expected_mats, long p) {
    for (size_t f = 0; f < sets.size(); ++f) {
      auto &Fset        = sets[f];
      auto &orb_indices = sym_set_orbitals[f];
      for (int i = 0; i < Fset.get_num_block_cols(); ++i) {
        int b_ix = Fset.get_block_index(i);
        if (b_ix != -1) {
          auto block = Fset.get_block(i);
          for (size_t k = 0; k < orb_indices.size(); ++k) {
            for (long l = 0; l < p; ++l) {
              auto expected_block =
                 expected_mats(orb_indices[k], l, range(block_starts[b_ix], block_starts[b_ix + 1]), range(block_starts[i], block_starts[i + 1]));
              ASSERT_LE(nda::max_element(nda::abs(block(k, l, _, _) - expected_block)), 1e-13);
            }
          }
        } else {
          for (int orb_index : orb_indices) {
            auto expected_block = expected_mats(orb_index, _, _, range(block_starts[i], block_starts[i + 1]));
            ASSERT_LE(nda::max_element(nda::abs(expected_block)), 1e-13);
          }
        }
      }
    }
  };

  check_sym_sets(Fq.Fs, expected_c_mats);
  check_sym_sets(Fq.F_dags, expected_cdag_mats);

  // --- Expected F_dag_bars and F_bars_refl ---
  // Contractions of the hybridization coefficients with the field operators, as in FSet::update_hybridization():
  //
  //   exp_F_dag_bars(m, l, :, :)  = +sum_k hyb(l, k, m) * cdag(k, :, :)
  //   exp_F_bars_refl(m, l, :, :) = -sum_k hyb(l, m, k) * c(k, :, :)
  //
  // with hyb_coeffs block diagonal with respect to the symmetry sets
  long p               = hyb_coeffs.extent(0);
  auto exp_F_dag_bars  = nda::zeros<dcomplex>(nflav, p, (long)N, (long)N);
  auto exp_F_bars_refl = nda::zeros<dcomplex>(nflav, p, (long)N, (long)N);
  for (long l = 0; l < p; ++l) {
    for (int m = 0; m < nflav; ++m) {
      for (int k = 0; k < nflav; ++k) {
        ASSERT_TRUE(sym_set_labels[k] == sym_set_labels[m] || std::abs(hyb_coeffs(l, k, m)) < 1.0e-13)
           << "hyb_coeffs(" << l << ", " << k << ", " << m << ") couples symmetry sets " << sym_set_labels[k] << " and " << sym_set_labels[m]
           << ", which the block-sparse storage cannot represent";
        exp_F_dag_bars(m, l, _, _) += hyb_coeffs(l, k, m) * expected_cdag_mats(k, _, _);
        exp_F_bars_refl(m, l, _, _) += -hyb_coeffs(l, m, k) * expected_c_mats(k, _, _); // minus sign convention for F_bars_refl
      }
    }
  }

  check_sym_set_bars(Fq.F_dag_bars, exp_F_dag_bars, p);
  check_sym_set_bars(Fq.F_bars_refl, exp_F_bars_refl, p);
}

/**
 * @brief The full Hamiltonian and its blocks for a model whose diagonalizing unitaries are complex
 *
 * @details Three sites with complex hoppings around a closed loop, so that no gauge makes the eigenvectors of the one- and two-particle
 * sectors real. The expected matrix is assembled from the Fock-space operator matrices, H = sum_ij h_ij c^dag_i c_j + U n_0 n_1. The
 * transformation of the diagonal energies back to the Fock basis must use the adjoint U^dagger, not the transpose U^T.
 */
TEST(AtomDiagUtils, complex_unitary_hamiltonian) {
  using dc = std::complex<double>;

  int norb = 3;
  double U = 0.7;

  nda::matrix<dc> h = {{0.10, dc(0.0, 0.30), dc(0.15, 0.0)}, {dc(0.0, -0.30), -0.20, dc(0.20, -0.10)}, {dc(0.15, 0.0), dc(0.20, 0.10), 0.35}};

  triqs::operators::many_body_operator_complex H;
  triqs::atom_diag::fundamental_operator_set fop_set;
  for (int i = 0; i < norb; ++i) { fop_set.insert("up", i); }
  for (int i = 0; i < norb; ++i) {
    for (int j = 0; j < norb; ++j) { H += h(i, j) * c_dag("up", i) * c("up", j); }
  }
  H += U * n("up", 0) * n("up", 1);

  triqs::atom_diag::atom_diag<true> ad(H, fop_set);

  // The unitaries are complex, otherwise this test cannot tell U^T from U^dagger
  double max_imag_U = 0.0;
  for (int s = 0; s < ad.n_subspaces(); ++s) {
    auto Us = ad.get_unitary_matrix(s);
    for (int i = 0; i < Us.extent(0); ++i) {
      for (int j = 0; j < Us.extent(1); ++j) { max_imag_U = std::max(max_imag_U, std::abs(Us(i, j).imag())); }
    }
  }
  ASSERT_GT(max_imag_U, 1e-3);

  // Expected Hamiltonian from the operator matrices
  auto N = ad.get_full_hilbert_space_dim();
  std::vector<nda::matrix<dcomplex>> c_mats, cdag_mats;
  for (int i = 0; i < norb; ++i) {
    c_mats.push_back(get_full_operator_matrix(ad, i, false));
    cdag_mats.push_back(get_full_operator_matrix(ad, i, true));
  }
  nda::matrix<dcomplex> H_expected = nda::zeros<dcomplex>(N, N);
  for (int i = 0; i < norb; ++i) {
    for (int j = 0; j < norb; ++j) { H_expected += h(i, j) * nda::matrix<dcomplex>(cdag_mats[i] * c_mats[j]); }
  }
  H_expected += U * nda::matrix<dcomplex>(cdag_mats[0] * c_mats[0] * cdag_mats[1] * c_mats[1]);

  auto H_mat = get_full_h_atomic(ad);
  EXPECT_LE(nda::max_element(nda::abs(H_mat - nda::dagger(H_mat))), 1e-13) << "the full Hamiltonian must be hermitian";
  EXPECT_LE(nda::max_element(nda::abs(H_mat - H_expected)), 1e-13);

  // The same Hamiltonian block by block
  auto [H_blocks, H_block_inds] = get_hamiltonian_blocks(ad);
  ASSERT_EQ(H_blocks.size(), ad.n_subspaces());
  for (int s = 0; s < ad.n_subspaces(); ++s) {
    auto fock_states = ad.get_fock_states(s);
    for (int i = 0; i < fock_states.size(); ++i) {
      for (int j = 0; j < fock_states.size(); ++j) {
        EXPECT_LE(std::abs(H_blocks[s](i, j) - H_expected(fock_states[i], fock_states[j])), 1e-13) << "block " << s << ", entry (" << i << "," << j << ")";
      }
    }
  }
}
