#include <gtest/gtest.h>

#include <triqs_xca/atom_diag_utils.hpp>

using nda::range;

using cppdlr::_;
using cppdlr::build_dlr_rf;
using cppdlr::imtime_ops;
using cppdlr::k_it;

using triqs::operators::n;
using triqs::operators::c;
using triqs::operators::c_dag;

using triqs_xca::atom_diag::get_operators;
using triqs_xca::atom_diag::get_full_h_atomic;
using triqs_xca::atom_diag::get_full_operator_matrix;
using triqs_xca::atom_diag::get_hamiltonian_blocks;

/**
 * @brief Creates a two-orbital Hamiltonian with spin and constructs the atom_diag object.
 *
 * @details Builds H = sum_i [ U n_up,i n_do,i + mu (n_up,i + n_do,i) + V (c†_up,i c_do,i + h.c.) ]
 * with norb=2, mu=0.25, U=1.0, V=0.1 by default. Orbital ordering: do 0, do 1, up 0, up 1.
 *
 * @param[in] norb Number of orbitals (default 2)
 * @param[in] mu Chemical potential (default 0.25)
 * @param[in] U On-site interaction strength (default 1.0)
 * @param[in] V Inter-orbital coupling strength (default 0.1)
 * @return triqs::atom_diag::atom_diag<false> object representing the Hamiltonian
 */
triqs::atom_diag::atom_diag<false> make_two_orbital_ad(int norb = 2, double mu = 0.25, double U = 1.0, double V = 0.1) {

  triqs::operators::many_body_operator_real H;
  triqs::atom_diag::fundamental_operator_set fop_set;

  // Build Hamiltonian and fundamental operator set
  for (int i = 0; i < norb; ++i) {
    H += U * n("up", i) * n("do", i) + mu * (n("up", i) + n("do", i)) + V * (c_dag("up", i) * c("do", i) + c_dag("do", i) * c("up", i));
    fop_set.insert("do", i);
  }
  for (int i = 0; i < norb; ++i) { fop_set.insert("up", i); }

  return {H, fop_set}; // triqs::atom_diag::atom_diag<false>(H, fop_set);
}

/**
 * @brief Builds DLR hybridization coefficients for the two-orbital model.
 *
 * Constructs a 4x4 hybridization function Delta(tau) on the DLR grid from two bath levels
 * e = {-2.3, 2.3} with hopping t=1.0 and inter-orbital coupling s=0.5, at beta=2.0
 * and DLR cutoff Lambda=20. Returns the DLR coefficients of Delta(tau).
 */
nda::array<dcomplex, 3> make_hyb_coeffs() {
  double s      = 0.5;
  double t      = 1.0;
  double beta   = 2.0;
  double Lambda = 10 * beta;
  double eps    = 1.0e-6;
  int norb      = 2;
  nda::array<double, 1> e{-2.3 * t, 2.3 * t};

  auto dlr_rf        = build_dlr_rf(Lambda, eps);
  auto itops         = imtime_ops(Lambda, dlr_rf);
  auto const &dlr_it = itops.get_itnodes();
  auto dlr_it_abs    = cppdlr::rel2abs(dlr_it);
  int r              = itops.rank();

  auto Jt = nda::array<dcomplex, 3>(r, 1, 1);
  for (int i = 0; i <= 1; i++) {
    for (int u = 0; u < r; u++) { Jt(u, 0, 0) += k_it(dlr_it_abs(u), e(i), beta); }
  }

  // orbital index order: do 0, do 1, up 0, up 1. same level <-> same parity index
  auto Deltat = nda::array<dcomplex, 3>(r, 2 * norb, 2 * norb);
  for (int i = 0; i < Deltat.extent(1); i++) {
    for (int j = i; j < Deltat.extent(2); j++) {
      if (i == j) {
        Deltat(_, i, j) = Jt(_, 0, 0);
      } else if ((i == 0 && j == 1) || (i == 1 && j == 0) || (i == 2 && j == 3) || (i == 3 && j == 2)) {
        Deltat(_, i, j) = s * Jt(_, 0, 0);
      }
    }
  }
  Deltat = t * t * Deltat;

  return itops.vals2coefs(Deltat);
}

/**
 * @brief Builds expected annihilation and creation operator matrices in the Fock basis.
 *
 * For 2*norb fermionic modes, constructs the N x N matrix representation of c_oidx and c†_oidx
 * (where N = 2^(2*norb)) using the standard fermionic anticommutation sign convention.
 *
 * @param[in] norb Number of orbitals (total flavors = 2*norb for spin-1/2)
 * @return Pair of (c_mats, cdag_mats), each of shape (2*norb, N, N)
 */
std::pair<nda::array<double, 3>, nda::array<double, 3>> make_expected_fock_operators(int norb) {
  int nflav      = 2 * norb;    // number of particle flavors (spin up and down for each orbital)
  long N         = 1L << nflav; // 2^(2*norb) total Fock states
  auto c_mats    = nda::zeros<double>(nflav, N, N);
  auto cdag_mats = nda::zeros<double>(nflav, N, N);

  // Slick way of filling in the c and c† matrices using bit manipulation to determine signs and state transitions generated by Claude
  // This has been verified to produce the same matrices as from a previous atom_diag python run.
  for (int oidx = 0; oidx < nflav; ++oidx) {
    for (long n = 0; n < N; ++n) {
      if (n & (1L << oidx)) {
        long m                = n ^ (1L << oidx);
        int sign              = (__builtin_popcountl(n & ((1L << oidx) - 1)) % 2 == 0) ? 1 : -1;
        c_mats(oidx, m, n)    = sign;
        cdag_mats(oidx, n, m) = sign;
      }
    }
  }
  return {std::move(c_mats), std::move(cdag_mats)};
}

/**
 * @brief Tests the computation of the full Hamiltonian and operator matrices from the atom_diag object.
 * 
 * This test creates a simple two-orbital Hamiltonian with known parameters, constructs the corresponding atom_diag object, and then uses the 
 * get_full_h_atomic and get_full_operator_matrix functions to compute the full Hamiltonian and operator matrices. The results are compared against 
 * expected matrices that were generated from a reference atom_diag python run. The test checks that the computed matrices match the expected ones 
 * within numerical precision limits.
 */
TEST(AtomDiagUtils, get_matrices) {
  // --- atom_diag setup ---
  int norb = 2;
  auto ad  = make_two_orbital_ad();

  // --- Get full Hamiltonian and operator matrices ---
  // Get full Hamiltonian matrix
  auto H_mat    = get_full_h_atomic(ad);
  std::size_t N = H_mat.extent(0);
  // The Hamiltonian has spin, so there are 2 * norb particle flavors
  nda::array<double, 3> c_mats(2 * norb, N, N), cdag_mats(2 * norb, N, N);
  for (int oidx = 0; oidx < 2 * norb; ++oidx) {
    auto c_mat            = get_full_operator_matrix(ad, oidx, false);
    auto cdag_mat         = get_full_operator_matrix(ad, oidx, true);
    c_mats(oidx, _, _)    = c_mat;
    cdag_mats(oidx, _, _) = cdag_mat;
  }

  // --- Expected matrices ---
  // Expected Hamiltonian matrix generated from atom_diag python run
  auto expected_H_mat    = nda::zeros<double>((long)N, (long)N);
  expected_H_mat(1, 1)   = 0.25;
  expected_H_mat(1, 4)   = 0.1;
  expected_H_mat(2, 2)   = 0.25;
  expected_H_mat(2, 8)   = 0.1;
  expected_H_mat(3, 3)   = 0.5;
  expected_H_mat(3, 6)   = -0.1;
  expected_H_mat(3, 9)   = 0.1;
  expected_H_mat(4, 1)   = 0.1;
  expected_H_mat(4, 4)   = 0.25;
  expected_H_mat(5, 5)   = 1.5;
  expected_H_mat(6, 3)   = -0.1;
  expected_H_mat(6, 6)   = 0.5;
  expected_H_mat(6, 12)  = -0.1;
  expected_H_mat(7, 7)   = 1.75;
  expected_H_mat(7, 13)  = -0.1;
  expected_H_mat(8, 2)   = 0.1;
  expected_H_mat(8, 8)   = 0.25;
  expected_H_mat(9, 3)   = 0.1;
  expected_H_mat(9, 9)   = 0.5;
  expected_H_mat(9, 12)  = 0.1;
  expected_H_mat(10, 10) = 1.5;
  expected_H_mat(11, 11) = 1.75;
  expected_H_mat(11, 14) = -0.1;
  expected_H_mat(12, 6)  = -0.1;
  expected_H_mat(12, 9)  = 0.1;
  expected_H_mat(12, 12) = 0.5;
  expected_H_mat(13, 7)  = -0.1;
  expected_H_mat(13, 13) = 1.75;
  expected_H_mat(14, 11) = -0.1;
  expected_H_mat(14, 14) = 1.75;
  expected_H_mat(15, 15) = 3.0;

  // Expected creation and annihilation operator matrices from standard Fock-space representation
  auto [expected_c_mats, expected_cdag_mats] = make_expected_fock_operators(norb);

  ASSERT_LE(nda::max_element(nda::abs(H_mat - expected_H_mat)), 1e-13);
  ASSERT_LE(nda::max_element(nda::abs(c_mats - expected_c_mats)), 1e-13);
  ASSERT_LE(nda::max_element(nda::abs(cdag_mats - expected_cdag_mats)), 1e-13);
}

/**
 * @brief Tests the extraction of Hamiltonian blocks from the atom_diag object.
 * 
 * This test creates a simple two-orbital Hamiltonian with known parameters, constructs the corresponding atom_diag object, and then uses the 
 * get_hamiltonian_blocks function to extract the Hamiltonian blocks and their corresponding block indices. A block index of 0 at index i indicates 
 * that there is a nonzero block in block column i (which is also block row i, since H is block-diagonal). The results are compared against expected 
 * blocks and indices that were generated from a reference atom_diag python run. The test checks that the computed blocks and indices match the 
 * expected ones within numerical precision limits.
 */
TEST(AtomDiagUtils, hamiltonian_blocks) {
  // --- atom_diag setup ---
  auto ad = make_two_orbital_ad();

  // --- Get Hamiltonian blocks ---
  auto h_tuple    = get_hamiltonian_blocks(ad);
  auto blocks     = std::get<0>(h_tuple);
  auto block_inds = std::get<1>(h_tuple);

  // --- Expected blocks and indices ---
  std::vector<nda::matrix<double>> expected_blocks = {
     nda::matrix<double>{{
        0.0,
     }},
     nda::matrix<double>{{0.25, 0.1}, {0.1, 0.25}},
     nda::matrix<double>{{0.25, 0.1}, {0.1, 0.25}},
     nda::matrix<double>{{0.5, -0.1, 0.1, 0}, {-0.1, 0.5, 0, -0.1}, {0.1, 0, 0.5, 0.1}, {0, -0.1, 0.1, 0.5}},
     nda::matrix<double>{{1.5}},
     nda::matrix<double>{{1.5}},
     nda::matrix<double>{{1.75, -0.1}, {-0.1, 1.75}},
     nda::matrix<double>{{1.75, -0.1}, {-0.1, 1.75}},
     nda::matrix<double>{{3.0}}};

  nda::vector<int> expected_block_inds = {-1, 0, 0, 0, 0, 0, 0, 0, 0};

  for (size_t i = 0; i < blocks.size(); ++i) { ASSERT_LE(nda::max_element(nda::abs(blocks[i] - expected_blocks[i])), 1e-13); }
  ASSERT_EQ(block_inds, expected_block_inds);
}

/**
 * @brief Tests the construction of the BlockOpSymQuartet object containing the creation and annihilation operators.
 * 
 * This test creates a simple two-orbital Hamiltonian with known parameters, constructs the corresponding atom_diag object, constructs a 
 * set of hybridization coefficients, and then uses the get_operators function to construct the BlockOpSymQuartet object containing the creation and 
 * annihilation operators. The test checks that the resulting BlockOpSymQuartet has the expected symmetry set labels and that the operator blocks 
 * match expected blocks that were generated from a reference atom_diag python run, within numerical precision limits.
 */
TEST(AtomDiagUtils, operators) {
  // --- atom_diag setup ---
  auto ad = make_two_orbital_ad();

  // --- Hybridization setup ---
  auto hyb_coeffs = make_hyb_coeffs();

  // --- Get creation and annihilation operators ---
  auto [Fq, sym_set_labels] = get_operators(ad, hyb_coeffs);

  // --- Expected symmetry set labels ---
  nda::vector<int> expected_sym_set_labels{0, 1, 0, 1}; // do 0 and up 0 have the same sparsity pattern, as do do 1 and up 1
  ASSERT_EQ(sym_set_labels, expected_sym_set_labels);

  // --- Expected Fs and F_dags blocks ---
  auto [expected_c_mats_fock, expected_cdag_mats_fock] = make_expected_fock_operators(2);
  // Get Fock space sizes and build permutation from ad subspace ordering to original Fock basis
  std::vector<size_t> fock_sizes;
  std::vector<long> perm; // perm[i] = original Fock state index at position i in subspace-ordered basis
  for (int s = 0; s < ad.n_subspaces(); ++s) {
    auto fock_states = ad.get_fock_states(s);
    fock_sizes.push_back(fock_states.size());
    for (auto state : fock_states) { perm.push_back(static_cast<long>(state)); }
  }
  // Build block_starts from fock_sizes
  std::vector<size_t> block_starts;
  for (int s = 0; s < ad.n_subspaces(); ++s) { block_starts.push_back(block_starts.empty() ? 0 : block_starts.back() + fock_sizes[s - 1]); }
  size_t N = block_starts.back() + fock_sizes.back();
  block_starts.push_back(N); // add end index for easy slicing

  // Permute expected matrices into ad subspace ordering
  long nflav = expected_c_mats_fock.extent(0);
  auto expected_c_mats    = nda::zeros<double>(nflav, (long)N, (long)N);
  auto expected_cdag_mats = nda::zeros<double>(nflav, (long)N, (long)N);
  for (int oidx = 0; oidx < nflav; ++oidx) {
    for (size_t i = 0; i < N; ++i) {
      for (size_t j = 0; j < N; ++j) {
        expected_c_mats(oidx, i, j)    = expected_c_mats_fock(oidx, perm[i], perm[j]);
        expected_cdag_mats(oidx, i, j) = expected_cdag_mats_fock(oidx, perm[i], perm[j]);
      }
    }
  }

  // Build mapping from symmetry set index to orbital indices
  std::vector<std::vector<int>> sym_set_orbitals(Fq.Fs.size());
  for (int i = 0; i < sym_set_labels.size(); ++i) { sym_set_orbitals[sym_set_labels[i]].push_back(i); }

  // Helper: compare BlockOpSymSet (3D blocks) against dense expected matrix (nflav x N x N)
  auto check_sym_sets = [&](const auto &sets, const auto &expected_mats) {
    for (size_t f = 0; f < sets.size(); ++f) {
      auto &Fset        = sets[f];
      auto &orb_indices = sym_set_orbitals[f];
      for (int i = 0; i < Fset.get_num_block_cols(); ++i) {
        int b_ix = Fset.get_block_index(i);
        if (b_ix != -1) {
          auto block = Fset.get_block(i);
          for (size_t k = 0; k < orb_indices.size(); ++k) {
            auto expected_block = expected_mats(orb_indices[k], range(block_starts[b_ix], block_starts[b_ix + 1]),
                                                range(block_starts[i], block_starts[i + 1]));
            ASSERT_LE(nda::max_element(nda::abs(block(k, _, _) - expected_block)), 1e-13);
          }
        } else {
          for (int orb_index : orb_indices) {
            auto expected_block = expected_mats(orb_index, _, range(block_starts[i], block_starts[i + 1]));
            ASSERT_LE(nda::max_element(nda::abs(expected_block)), 1e-13);
          }
        }
      }
    }
  };

  // Helper: compare BlockOpSymSetBar (4D blocks) against dense expected matrix (nflav x p x N x N)
  auto check_sym_set_bars = [&](const auto &sets, const auto &expected_mats, long p) {
    for (size_t f = 0; f < sets.size(); ++f) {
      auto &Fset        = sets[f];
      auto &orb_indices = sym_set_orbitals[f];
      for (int i = 0; i < Fset.get_num_block_cols(); ++i) {
        int b_ix = Fset.get_block_index(i);
        if (b_ix != -1) {
          auto block = Fset.get_block(i);
          for (size_t k = 0; k < orb_indices.size(); ++k) {
            for (long l = 0; l < p; ++l) {
              auto expected_block = expected_mats(orb_indices[k], l, range(block_starts[b_ix], block_starts[b_ix + 1]),
                                                  range(block_starts[i], block_starts[i + 1]));
              ASSERT_LE(nda::max_element(nda::abs(block(k, l, _, _) - expected_block)), 1e-13);
            }
          }
        } else {
          for (int orb_index : orb_indices) {
            auto expected_block = expected_mats(orb_index, _, _, range(block_starts[i], block_starts[i + 1]));
            ASSERT_LE(nda::max_element(nda::abs(expected_block)), 1e-13);
          }
        }
      }
    }
  };

  check_sym_sets(Fq.Fs, expected_c_mats);
  check_sym_sets(Fq.F_dags, expected_cdag_mats);

  // --- Expected F_dag_bars and F_bars_refl ---
  // Precompute position of each orbital within its symmetry set
  std::vector<int> orbital_position(nflav);
  for (auto & sym_set_orbital : sym_set_orbitals) {
    for (size_t pos = 0; pos < sym_set_orbital.size(); ++pos) { orbital_position[sym_set_orbital[pos]] = pos; }
  }

  // exp_F_dag_bars(m, l, :, :) = sum_k hyb(l, k, m) * cdag(mapped_k, :, :)
  //   where mapped_k = sym_set_orbitals[set_of(m)][position_of(k)]
  // exp_F_bars_refl(k, l, :, :) = sum_m hyb(l, k, m) * c(mapped_m, :, :)
  //   where mapped_m = sym_set_orbitals[set_of(k)][position_of(m)]
  long p = hyb_coeffs.extent(0);
  auto exp_F_dag_bars  = nda::zeros<dcomplex>(nflav, p, (long)N, (long)N);
  auto exp_F_bars_refl = nda::zeros<dcomplex>(nflav, p, (long)N, (long)N);
  for (int m = 0; m < nflav; ++m) {
    int f_m = sym_set_labels[m];
    for (long l = 0; l < p; ++l) {
      for (int k = 0; k < nflav; ++k) {
        int mapped_k = sym_set_orbitals[f_m][orbital_position[k]];
        exp_F_dag_bars(m, l, _, _) += hyb_coeffs(l, k, m) * expected_cdag_mats(mapped_k, _, _);
      }
    }
  }
  for (int k = 0; k < nflav; ++k) {
    int f_k = sym_set_labels[k];
    for (long l = 0; l < p; ++l) {
      for (int m = 0; m < nflav; ++m) {
        int mapped_m = sym_set_orbitals[f_k][orbital_position[m]];
        exp_F_bars_refl(k, l, _, _) += -hyb_coeffs(l, k, m) * expected_c_mats(mapped_m, _, _); // minus sign convention for F_bars_refl
      }
    }
  }

  check_sym_set_bars(Fq.F_dag_bars, exp_F_dag_bars, p);
  check_sym_set_bars(Fq.F_bars_refl, exp_F_bars_refl, p);
}